<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(PortableTargetFramework)</TargetFramework>
      <!-- Disable C#13+ keyword "field" -->
    <LangVersion>13</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\app\GitCommands\GitCommands.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\GitExtUtils\GitExtUtils.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\GitUI\GitUI.csproj" />
    <ProjectReference Include="..\..\..\..\src\plugins\GitUIPluginInterfaces\GitUIPluginInterfaces.csproj" />
    <ProjectReference Include="..\..\..\..\src\app\ResourceManager\ResourceManager.csproj" />
    <ProjectReference Include="..\..\..\CommonTestUtils\CommonTestUtils.csproj" />
  </ItemGroup>

</Project>
