<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PortableTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\app\GitExtensions.Extensibility\GitExtensions.Extensibility.csproj" />
    <ProjectReference Include="..\..\..\CommonTestUtils\CommonTestUtils.csproj" />
  </ItemGroup>

</Project>
