<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PortableTargetFramework)</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Resources\git-extensions-logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitExtUtils\GitExtUtils.csproj" />
    <ProjectReference Include="..\GitUI.Avalonia\GitUI.Avalonia.csproj" />
    <ProjectReference Include="..\ResourceManager\ResourceManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitInfo">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
