<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PortableTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ben.Demystifier" />
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitExtensions.Extensibility\GitExtensions.Extensibility.csproj" />
  </ItemGroup>

</Project>
